### PR TITLE
[release-4.13] OCPBUGS-16250: Add management workloads annotations

### PR DESCRIPTION
**Pull request by Phaow**
This is a manual cherry-pick of https://github.com/openshift/ovirt-csi-driver-operator/pull/116 , fix the OCPBUGS-16250.

### CODE REVIEW

**Comment by Phaow** [comment]
@mburman5 Could you please help take a look and add the `cherry-pick-approved` when you get a chance? Thanks! BTW, do you know who can help add the `backport-risk-assessed` label?

**Comment by Phaow** [comment]
Checked the e2e job **[must-gather](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovirt-csi-driver-operator/120/pull-ci-openshift-ovirt-csi-driver-operator-release-4.13-e2e-ovirt/1686340404317786112/artifacts/e2e-ovirt/gather-must-gather/artifacts/)** the annotation already added and CI looks good. We're safe to go. @leistnerova could you please help to add the `cherry-pick-approved`. I'm also the bug QA contact, so I could verify and double confirm again.

```console
$ omg get deploy/ovirt-csi-driver-controller -oyaml|yq .spec.template.metadata.annotations
operator.openshift.io/dep-b3c68cb2620304d88e465c548c1c214a4acf8: O1lK1A==
operator.openshift.io/dep-c42c0d45eb927642d9a24aa98132ae4f8cacd: 8VUTtQ==
target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
```

**Comment by leistnerova** [comment]
/label cherry-pick-approved
Changes in metadata, no functional change. Verified by OCP QE

**Pull request merged**
