### PR TITLE
Bug 2049169: Add custom CA bundle support

### PR DESCRIPTION
**Pull request by jsafrane**
In OCP, it's possible to set a cluster-wide proxy that operators can use to communicate with external APIs [1]. In addition to that, users can also define a custom CA bundle to be used together with the proxy setting.

Currently, we are not using that custom CA bundle and this patch fixes that. The main benefit of injecting the CA bundle using the CSI controllers, as opposed to statically mount it using the manifest file, is that we can watch for changes in the trusted CA bundle store and roll out a new Deployment with the new CA bundle injected.

[1] https://docs.openshift.com/container-platform/4.10/networking/enable-cluster-wide-proxy.html

This PR needed new library-go, hence I updated it. It pulls new Kubernetes libs + go 1.17. As side effect of the new library-go, leader election in the operator changes from ConfigMap to ConfigMap + Lease, to be ready to move to Lease only leader election in 4.11. Nothing changes in the CSI sidecars.

This is a hot candidate for backport to 4.10, where all our CSI driver operators support CA bundle for proxy and we forgot about oVirt (sorry!).

@openshift/storage @janosdebugs @bennyz

### CODE REVIEW

**Comment by janosdebugs** [comment]
@jsafrane does this mean that the oVirt API calls should also go via this proxy? If yes we will need to implement this in the oVirt client library as we are preparing to do active monitoring for credentials changes.

**Comment by janosdebugs** [comment]
@jsafrane as for the backport, I'll need to take this up with QE and PM, without their ACK there can be no backport. How urgent is this?

**Comment by jsafrane** [comment]
> does this mean that the oVirt API calls should also go via this proxy

Sort of, proxy support was already done in https://github.com/openshift/ovirt-csi-driver-operator/pull/40 - when a proxy is configured, driver pods get HTTP*_PROXY env. vars. This PR only adds custom CA bundle, if the proxy is https one & the cluster has custom CA.

BTW, the operator code also restarts the driver pods when the proxy or the CA bundle changes, we don't expect anything smart from the driver.

> How urgent is this?

The CA bundle could probably wait for 4.10.z or even 4.11, but the leader election changes in library-go bump are in fact a bugfix that needs to be in 4.10. It has been soaked in CI for quite some time in the other operators and it is change is invisible to users.

**Comment by dobsonj** [comment]
/retest
failed in terraform setup like the other open PR

**Comment by janosdebugs** [comment]
> BTW, the operator code also restarts the driver pods when the proxy or the CA bundle changes, we don't expect anything smart from the driver.

This is interesting, we had customer cases complaining that this did not happen. Maybe something to look at.

**Review by janosdebugs — APPROVED** [review]
/lgtm

**Pull request merged**
