### PR TITLE
[4.12] OCPBUGS-18417: set TLS cipher suites in Kube RBAC sidecars

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/OCPBUGS-18417

- Bump library-go to get default TLS cipher suite list
- OCPBUGS-18417: set TLS cipher suites in Kube RBAC sidecars

cc @openshift/storage

### CODE REVIEW

**Comment by engelmi** [comment]
@leistnerova Could you apply the cherry pick approved label?
@eslutsky Could you apply the backport risk assessed label?

**Comment by duanwei33** [comment]
Checked CI result good and controller pod contains "tls-cipher-suites" in CI, looks good from QE side.

@leistnerova Could you help add the "cherry-pick-approved" label? Thanks!

**Comment by leistnerova** [comment]
Hi @duanwei33 I was not aware of any approved backport in OCP on RHV. How this should be tested?

**Comment by duanwei33** [comment]
Hi @leistnerova, this is the [CI job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_ovirt-csi-driver-operator/121/pull-ci-openshift-ovirt-csi-driver-operator-release-4.12-e2e-ovirt/1697336659172921344) I checked,  the "tls-cipher-suites" in present and the test result looks good. Do you think it is enough? (There is no function change)
 
```
$ w3m -dump 'https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovirt-csi-driver-operator/121/pull-ci-openshift-ovirt-csi-driver-operator-release-4.12-e2e-ovirt/1697336659172921344/artifacts/e2e-ovirt/gather-extra/artifacts/pods.json' | jq -r '.items[] | select(.metadata.name | match("ovirt-csi-driver-controller.*")).spec.containers[].args'  | grep tls-cipher-suites
  "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
  "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",

```

**Comment by dobsonj** [comment]
@leistnerova This resolves a CVE bug by dropping known insecure ciphers from the list of cipher suites that are accepted by Kube RBAC sidecars. Customers are noticing and asking for updates (see OCPBUGS-18417 ). The fix has already been in 4.13 for >9 months.

IMO, checking the ovirt-csi-driver-controller pods in the CI job as @duanwei33 did is sufficient to ensure the correct cipher list is passed to the controller deployment. That cipher list is consistent with all other CSI driver operators.

**Comment by leistnerova** [comment]
Thank you Wei and Jonathan for explanation. As this is no functional change, CI results are enough to verify and no further testing needed.
/label cherry-pick-approved

**Pull request merged**
