### PR TITLE
Use go:embed for static yaml file

### PR DESCRIPTION
**Pull request by jsafrane**
Move from bindata to go:embed.

### CODE REVIEW

**Comment by jsafrane** [comment]
I don't understand why go 1.15 is used for unit/verify tests

**Comment by Gal-Zaidman** [comment]
Can you also edit: https://github.com/openshift/ovirt-csi-driver-operator/blob/master/.ci-operator.yaml#L4
On master ci started using https://github.com/openshift/release/blob/master/ci-operator/config/openshift/ovirt-csi-driver-operator/openshift-ovirt-csi-driver-operator-master.yaml#L32

**Comment by jsafrane** [comment]
Thanks! Edited `.ci-operator.yaml`...

**Pull request merged**
