### PR TITLE
Bug 1879406: Use port 10300-10301 for liveness probes

### PR DESCRIPTION
**Pull request by jsafrane**
[9xxx range is allowed to be accessible from outside of nodes](https://github.com/openshift/openshift-docs/blob/master/modules/installation-network-user-infra.adoc) and we don't need that for CSI driver liveness probes.

Using 10300 does not make it blocked by firewall, but at least it's not in the list of open ports and it's blocked in IPI.

@openshift/storage, @bennyz @rgolangh

### CODE REVIEW

**Review by bennyz — APPROVED** [review]

**Comment by bennyz** [comment]
looks like CI failed on the xfs tests, to be fixed by https://github.com/openshift/ovirt-csi-driver/pull/47

**Comment by jsafrane** [comment]
/hold
the test failures look genuine

**Comment by jsafrane** [comment]
/hold cancel

* Fixed port number in liveness probe cmdline arguments.
* Added liveness probe to controller pod(s).

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
